import * as loader from './js/loader';
import * as watchedMovies from './js/watchedMovies';
// import * as pg from './js/pg';
import * as theme from './js/themeSwitcher';
import * as languageLibrary from './js/languageLibrary';
import * as modal from './js/modal';
import * as up from './js/up-btnAndSwitcher';
import * as footerTranslation from './js/footerTranslation';
import * as modalTeam from './js/modal-team';
import * as signIn from './js/switchSignInForms';
import * as authAndLoIn from './js/authAndLogIn';
import * as translateLibrary from './js/translateLibrary';
import * as translateForms from './js/translateAuthForms';
